@baseUrl = http://localhost:3333

### Create a new user ###
# @name create
POST {{baseUrl}}/gyms
Content-Type: application/json

{
  "title": "Gym Title Test",
  "description": null,
  "phone": null,
  "latitude": 0,
  "longitude": 0,
}
