version: '3'

services:
  portfolio-gym-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=dockerPass
      - POSTGRESQL_DATABASE=portfolio-gym